name: package_nuget

on:
  push:
    tags: ['v*']
  workflow_dispatch:

env:
  PROJECT_DIR: ${{ github.workspace }}/SimpleAudioPlayer

jobs:
  package_nuget:
    name: Package NuGet
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with: 
        dotnet-version: | 
          8.0.x
          9.0.x
        
    - name: Pack NuGet Package
      run: dotnet pack "${{ env.PROJECT_DIR }}/SimpleAudioPlayer.csproj" -c Release -p:PackageId=SimpleAudioPlayer -o "${{ github.workspace }}/artifacts/nuget"

    - name: Publish NuGet Package
      run: |
        for package in "${{ github.workspace }}"/artifacts/nuget/*.nupkg; do
          dotnet nuget push "$package" \
            --source "https://api.nuget.org/v3/index.json" \
            --api-key "${{ secrets.NUGET_API_KEY }}" \
            --skip-duplicate
        done
    
